fos_rest:
  routing_loader:
    include_format: false
  param_fetcher_listener: true
  body_listener:
    enabled:        true
    default_format: json
  view:
    view_response_listener: 'force'
    formats:
      json: true
      jsonp: true
      xml: true
    templating_formats:
      html: true
      css: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json', 'jsonp', 'xml', 'text/html', 'text/css'], fallback_format: json, prefer_extension: false }
  exception:
    enabled: true